services:
  app:
    build:
      args:
        SWAY_UNSUPPORTED_GPU: true
    environment:
      - RENDER_GROUP_GID=
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
